### ISSUE TITLE
Recompile d2gs got kicked by flooding server

### ISSUE THREAD

**Issue by andersgong** [RElesgoe/d2gs#2]
I recompile your version of d2gs&pvpgn，and use your d2server.dll in bin, then I can enter the game, but got kicked by flooding server, what can I do? thanks!

**Comment by RElesgoe** [comment]
What version of D2 are you using to play?

**Comment by andersgong** [comment]
> 
> 
> What version of D2 are you using to play?

1.13d, I want to know the detail of how to solve it, very thanks!

**Comment by RElesgoe** [comment]
I'm not sure why you're experiencing this problem, it _shouldn't_ happen.
