### ISSUE TITLE
About d2server.dll

### ISSUE THREAD

**Issue by swordow** [RElesgoe/d2gs#4]
Is the d2server.dll used by marsgod same with that from Onlyer's source code? Or they come from the origin d2server.dll, but the original d2server.dll has 180kb..

**Comment by RElesgoe** [comment]
The `d2server.dll` in the `bin` directory is based on d2gs 1.13d by Marsgod found at https://harpywar.com/?a=articles&b=2&c=2&d=21&lang=ru

The only changes are patches to make it compatible with a recompiled D2GS program.

**Comment by swordow** [comment]
i found the d2gs.exe.c in repo, what's the version? i decompolied the d2gs.exe from marsgod 1.11b build 46 and updated the code logic to d2gs109 source code, but it crashed somewhere while entering the room...

**Comment by RElesgoe** [comment]
> i found the d2gs.exe.c in repo, what's the version?

It's whatever the latest D2GS.exe is, which was last modified on 2004-03-04.

**Comment by RElesgoe** [comment]
I think your problem is that you didn't update all the callback functions' function signature. I think I also had this problem until I found the correct signatures in d2server.dll.

https://github.com/RElesgoe/d2gs/blob/master/include/d2gelib/d2server.h#L205-L253

https://github.com/swordow/d2gs110/blob/master/include/d2gelib/d2server.h#L112-L160

**Comment by swordow** [comment]
emmm, the function signature seems be same with it in d2server.dll (i decompiled in static.). And i compared with them in your code, i found the only different signature is the function "FindPlayerToken", yours has two extra parameters, although they are not used. But i could not found the extra two args passed in d2server.dll or d2gs.exe(used in marsgod1.11b build 46), where you find the extra parameters?

**Comment by RElesgoe** [comment]
The function names and parameter names happened to be stored as plain strings in the dll.

If I open d2server.dll 1.11b build 46 by marsgod with Ghidra, I can clearly see all the parameters:
![image](https://user-images.githubusercontent.com/1463845/110407590-f745c200-8038-11eb-99f0-95fb4a9ba890.png)

You can also open the dll with a hex editor and go to address 0x0000de94

**Comment by swordow** [comment]
Thanks. I also found this table in IDA, but the decompiled code shows that the FindPlayToken function only push five args...
![image](https://user-images.githubusercontent.com/7107003/110410720-4dac1280-80c4-11eb-9cef-877f7f351fed.png)

**Comment by RElesgoe** [comment]
Indeed very confusing

**Comment by swordow** [comment]
After I fixed the FindPlayerToken signature, it works.....

**Comment by RElesgoe** [comment]
Why do you have issues disabled in your repository? I have a bug or two to report

**Comment by swordow** [comment]
> Why do you have issues disabled in your repository? I have a bug or two to report

I just forked from pvpgn/d2gs109, i have opened it now.:-)
