### ISSUE TITLE
Cannot compile the project

### ISSUE THREAD

**Issue by Happin3ss** [RElesgoe/d2gs#5]
Hi, I used Visual Studio 2019 to compile the project but got some strange error as below:
![image](https://user-images.githubusercontent.com/17236895/109384214-d802b280-791d-11eb-9d51-5ceb6fcc87e9.png)
Do you have any suggestion ?

And I suggest it can be better if we have a precompiled build of this D2GS and put it probably into release section

**Comment by RElesgoe** [comment]
I haven't experienced this problem before.

How are you generating project files? If you let Visual Studio run CMake for you, it'll default to 64-bit build with the Ninja generator. If that's the case, make sure you change the settings to build 32-bit with Visual Studio generator.

**Comment by Happin3ss** [comment]
Hi @RElesgoe , I got the below error after setting the build target to 32-bit
![image](https://user-images.githubusercontent.com/17236895/109506003-bfd29500-7acf-11eb-8380-4636fc9a71b5.png)

I have to admit that I'm totally not familiar with C++ building stuffs. Reading code will not be a problem but building is quite challenge. So I would appreciate if you update the README with an in-depth steps to compile it.

**Comment by RElesgoe** [comment]
I assume you allowed Visual Studio to use its internal CMake to generate project files for you.

Do either:

**Option 1**
From within Visual Studio's solution explorer, open CMakeSettings.json
Scroll down and click _Show advanced settings_
Under **CMake generator:**, click on the dropdown box and change its value from **Ninja** to **Visual Studio 16 2019**

**Option 2**
Open CMakeSettings.json with a text editor
Look for each "generator" key and change its value from **Ninja** to **Visual Studio 16 2019**

**Comment by Happin3ss** [comment]
Thanks a lot !
